# Conexión a MS SQL Server en Docker
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=residencial_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=TuPasswordSeguro123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate: Crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Habilitar Swagger para pruebas locales
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081