classDiagram
    direction TB
    class ReservaController {
        +registrarReserva(dto, fotoAnverso, fotoReverso)
    }
    class ReservaService {
        +registrarReserva(dto, fotoAnverso, fotoReverso)
        -validarDisponibilidad(habitacionId)
    }
    class FileStorageService {
        +guardar(MultipartFile) String
    }
    class Huesped {
        -String nombre
        -String ci
        -String celular
        -String urlFotoAnverso
        -String urlFotoReverso
    }
    class Reserva {
        -LocalDate fechaCreacion
        -LocalDate fechaIngreso
        -Integer cantidadBloques
        -Double montoTotal
        -String estado
    }
    class Habitacion {
        -String numero
        -String estadoActual
        +bloquear()
    }
    class TipoHabitacion {
        -String nombreTipo
        -Double precioBase
        -String descripcion
    }

    ReservaController --> ReservaService
    ReservaService --> FileStorageService : Fabricación Pura
    ReservaService --> Huesped : Experto
    ReservaService --> Reserva : Creador
    Reserva "1" --> "1" Habitacion : se asigna a
    Habitacion "*" --> "1" TipoHabitacion : Patrón de Descripción