@startuml
title Diseño de Secuencia: CU-01 Consultar Disponibilidad

participant "view:DisponibilidadView" as UI
participant "ctrl:DisponibilidadController" as Ctrl
participant "service:DisponibilidadService" as Serv
participant "repo:HabitacionRepository" as Repo
participant "listaHabitaciones:List<Habitacion>" as List

UI -> Ctrl : onSearch(fecha, tipoNombre)
activate Ctrl

Ctrl -> Serv : buscarDisponibles(fecha, tipoNombre)
activate Serv

Serv -> Repo : findAvailableByTipo(fecha, tipoNombre)
activate Repo
Repo -->> Serv : listaHabitaciones
deactivate Repo

Note over Serv: El servicio filtra según el \nPatrón de Descripción (TipoHabitacion)

Serv -->> Ctrl : listaHabitaciones
deactivate Serv

Ctrl -->> UI : mostrarResultados(listaHabitaciones)
deactivate Ctrl

@enduml