@startuml
title Diagrama de Colaboración: CU-01

agent "Recepcionista" as R
boundary "DisponibilidadView" as UI
control "DisponibilidadController" as Ctrl
entity "DisponibilidadService" as Serv
database "HabitacionRepository" as Repo

R -> UI : 1: buscar(fecha, tipo)
UI -> Ctrl : 2: onSearch(fecha, tipo)
Ctrl -> Serv : 3: buscarDisponibles(fecha, tipo)
Serv -> Repo : 4: findAvailable(fecha, tipo)
@enduml